name: Despliegue a S3 y CloudFront

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'LICENSE'
      - 'README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Validate HTML files
      run: |
        for file in index.html error.html; do
          if [ ! -f "$file" ]; then
            echo "Error: $file no encontrado"
            exit 1
          fi
          if ! grep -q "<!DOCTYPE html>" "$file"; then
            echo "Error: $file no parece ser un HTML válido"
            exit 1
          fi
        done

    - name: Sync files to S3 bucket
      run: |
        aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME }} \
          --exclude "*" \
          --include "index.html" \
          --include "error.html"

    - name: Debug CloudFront Distributions
      run: |
        aws cloudfront list-distributions | jq .

    - name: Create CloudFront Distribution (if not exists)
      run: |
        DISTRIBUTION_ID=$(aws cloudfront list-distributions | jq -r --arg domain "${{ secrets.S3_BUCKET_NAME }}.s3.amazonaws.com" '.DistributionList.Items[] | select(.Origins.Items[0].DomainName == $domain) | .Id')

        if [ -z "$DISTRIBUTION_ID" ]; then
          echo "No existe una distribución de CloudFront para el bucket. Creándola..."
          aws cloudfront create-distribution \
            --origin-domain-name "${{ secrets.S3_BUCKET_NAME }}.s3.amazonaws.com" \
            --default-root-object index.html \
            --output json | jq -r '.Distribution.Id'
        else
          echo "La distribución de CloudFront ya existe: $DISTRIBUTION_ID"
        fi

    - name: Invalidate CloudFront cache
      run: |
        DISTRIBUTION_ID=$(aws cloudfront list-distributions | jq -r --arg domain "${{ secrets.S3_BUCKET_NAME }}.s3.amazonaws.com" '.DistributionList.Items[] | select(.Origins.Items[0].DomainName == $domain) | .Id')

        if [ -n "$DISTRIBUTION_ID" ]; then
          aws cloudfront create-invalidation \
            --distribution-id $DISTRIBUTION_ID \
            --paths "/*"
          echo "Invalidación del caché de CloudFront completada."
        else
          echo "Error: No se pudo encontrar una distribución de CloudFront para invalidar el caché."
          exit 1
        fi

    - name: Verify Deployment
      run: |
        # Verificar que los archivos estén en S3
        aws s3 ls s3://${{ secrets.S3_BUCKET_NAME }}

        # Obtener la URL de CloudFront
        CLOUDFRONT_URL=$(aws cloudfront list-distributions | jq -r --arg domain "${{ secrets.S3_BUCKET_NAME }}.s3.amazonaws.com" '.DistributionList.Items[] | select(.Origins.Items[0].DomainName == $domain) | .DomainName')

        if [ -z "$CLOUDFRONT_URL" ]; then
          echo "Error: No se pudo encontrar una URL de CloudFront."
          exit 1
        fi

        echo "CloudFront URL: https://$CLOUDFRONT_URL"

        # Intentar obtener los archivos
        curl -f https://$CLOUDFRONT_URL/index.html
        curl -f https://$CLOUDFRONT_URL/error.html
